controller:
  admin:
    existingSecret: jenkins-secret
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password

  installPlugins:
    - kubernetes
    - workflow-job
    - workflow-aggregator
    - job-dsl
    - git
    - blueocean
    - configuration-as-code

  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: jenkins.example.com
    path: /
    pathType: Prefix
    tls:
      - hosts:
          - jenkins.example.com
        secretName: jenkins-tls

  persistence:
    enabled: true
    storageClassName: ebs-csi-sc
    size: 10Gi
    existingClaim: ""

  JCasC:
    enabled: true
    configScripts:
      kubernetes-agent: |
        jenkins:
          clouds:
            - kubernetes:
                name: "eks"
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
                containerCapStr: "10"
                templates:
                  - name: "default"
                    label: "jenkins-agent"
                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        args: "\${computer.jnlpmac} \${computer.name}"
                        ttyEnabled: true
                        resourceRequestCpu: "200m"
                        resourceRequestMemory: "512Mi"

