auth:
  existingSecret: postgres-secret
  secretKeys:
    user: postgres-user
    password: postgres-password
    database: postgres-db

primary:
  persistence:
    enabled: true
    storageClass: gp2
    size: 8Gi

  initdbScripts:
    init.sql: |
      CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        username TEXT NOT NULL,
        email TEXT NOT NULL
      );

      INSERT INTO users (username, email) VALUES ('admin', 'admin@example.com')
      ON CONFLICT DO NOTHING;